# Generated by Django 4.2.2 on 2023-06-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Logo Title', max_length=40)),
                ('logo_img', models.ImageField(upload_to='midea/images/')),
                ('logo_alt', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
